services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"  # MQTT Port
    networks:
      - home_network
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    volumes:
      - ./homeassistant/config:/config
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8123:8123"  # Port für Home Assistant
    networks:
      - home_network

networks:
  home_network:
    driver: bridge
